/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/maps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Maps
         * @description List available maps with name, size, and region.
         */
        get: operations["list_maps_maps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/{map_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Map
         * @description Full map detail including geometry. Omits stops/routes.
         */
        get: operations["get_map_maps__map_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Game
         * @description Create a new game on a map. The host is automatically added as the first player.
         */
        post: operations["create_game_games_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Join Game
         * @description Join a game by its join code.
         */
        post: operations["join_game_games_join_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Game State
         * @description Fetch current game state.
         */
        get: operations["get_game_state_games__game_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session Info
         * @description Validate stored session credentials. Returns player info and game status.
         */
        get: operations["get_session_info_games__game_id__me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Inventory
         * @description Current question inventory — all slots grouped by type.
         */
        get: operations["get_inventory_games__game_id__inventory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Player
         * @description Remove a player from the lobby. Self-leave or host-kick.
         */
        delete: operations["remove_player_games__game_id__players__player_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Player
         * @description Update a player's role, name, color, or device token.
         */
        patch: operations["patch_player_games__game_id__players__player_id__patch"];
        trace?: never;
    };
    "/games/{game_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Game
         * @description Transition the game from lobby to hiding. Host-only.
         */
        post: operations["start_game_games__game_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End Game
         * @description Transition the game to finished.
         */
        post: operations["end_game_games__game_id__end_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/hider-station": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Hider Station
         * @description The hider's station and election status. Available during hiding and seeking.
         */
        get: operations["get_hider_station_games__game_id__hider_station_get"];
        put?: never;
        /**
         * Elect Hider Station
         * @description Elect a station as the hider's hiding zone anchor. Permanent.
         */
        post: operations["elect_hider_station_games__game_id__hider_station_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/nearby-stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Nearby Stations
         * @description Playable stops within hiding zone radius of a point, with hiding zone polygons.
         */
        get: operations["get_nearby_stations_games__game_id__nearby_stations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/hiding-zone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Hiding Zone
         * @description Hiding zone polygon for a given station.
         */
        get: operations["get_hiding_zone_games__game_id__hiding_zone_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Effective Map
         * @description Effective map with transit data and exclusions applied.
         */
        get: operations["get_effective_map_games__game_id__map_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/candidate-stations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Candidate Stations
         * @description Playable stops whose hiding zone circle is not fully covered by exclusion zones.
         */
        get: operations["list_candidate_stations_games__game_id__candidate_stations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/location": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report Location
         * @description Report the caller's location. Updates are broadcast via SSE.
         */
        post: operations["report_location_games__game_id__location_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/location-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Location History
         * @description Full location log for post-game replay. Only available when finished.
         */
        get: operations["location_history_games__game_id__location_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/questions/radar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask Radar Question
         * @description Ask a radar question, spending a radar inventory slot.
         */
        post: operations["ask_radar_question_games__game_id__questions_radar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/questions/thermometer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask Thermometer Question
         * @description Ask a thermometer question, spending a thermometer inventory slot.
         */
        post: operations["ask_thermometer_question_games__game_id__questions_thermometer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/questions/matching": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask Matching Question
         * @description Ask a matching question about a feature category.
         */
        post: operations["ask_matching_question_games__game_id__questions_matching_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/questions/measuring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask Measuring Question
         * @description Ask a measuring question about a feature category.
         */
        post: operations["ask_measuring_question_games__game_id__questions_measuring_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/questions/thermometer/{question_id}/lock-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lock In Question
         * @description Lock in the seeker's end position for a thermometer question.
         */
        post: operations["lock_in_question_games__game_id__questions_thermometer__question_id__lock_in_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/questions/{question_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer Question
         * @description Hider answers a question — snapshot location, compute answer and exclusion.
         */
        post: operations["answer_question_games__game_id__questions__question_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/questions/{question_id}/veto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Veto Question
         * @description Hider vetoes a question — no answer, no exclusion zone.
         *
         *     With scheduled=true, the veto is deferred: it fires when the auto-answer
         *     timer expires instead of immediately. The hider can still answer normally
         *     before the timer to cancel the scheduled veto implicitly.
         */
        post: operations["veto_question_games__game_id__questions__question_id__veto_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/questions/{question_id}/abandon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abandon Question Endpoint
         * @description Seeker abandons a question — no answer, no exclusion zone.
         */
        post: operations["abandon_question_endpoint_games__game_id__questions__question_id__abandon_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Game Questions
         * @description Chronological list of all questions — whitelist summary only.
         */
        get: operations["list_game_questions_games__game_id__questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/questions/{question_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Question Detail
         * @description Full question detail — hider only.
         */
        get: operations["get_question_detail_games__game_id__questions__question_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/exclusions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Exclusions
         * @description Seeker tactical map — per-question exclusion geometry.
         */
        get: operations["get_exclusions_games__game_id__exclusions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/endgame-exclusions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Endgame Exclusions
         * @description Endgame exclusion view: per-question exclusions intersected with a hiding zone circle.
         */
        get: operations["endgame_exclusions_games__game_id__endgame_exclusions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AskQuestionRequest
         * @description Ask a question, identified by slot_index. The URL determines question_type.
         */
        AskQuestionRequest: {
            /**
             * Slot Index
             * @description 0-based index into the inventory for this question type.
             */
            slot_index: number;
            /** @description Current seeker position as a GeoJSON Point. */
            location: components["schemas"]["Point"];
            /**
             * Custom Distance
             * @description Required for custom slots (distance=null).
             */
            custom_distance?: number | null;
        };
        /**
         * AskQuestionResponse
         * @description Slim response for ask endpoints — only fields meaningful at ask time.
         *
         *     No answer-time fields (seeker_location_end, hider_location, answered_at, answer).
         */
        AskQuestionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Game Id
             * Format: uuid
             */
            game_id: string;
            /**
             * Sequence
             * @description 1-based chronological order within the game.
             */
            sequence: number;
            question_type: components["schemas"]["QuestionType"];
            status: components["schemas"]["QuestionStatus"];
            /**
             * Ask Count
             * @description Which attempt this was (1 = first ask).
             */
            ask_count: number;
            /**
             * Parameters
             * @description Type-specific question parameters.
             */
            parameters: components["schemas"]["RadarParamsResponse"] | components["schemas"]["ThermometerParamsResponse"] | components["schemas"]["FeatureParamsResponse"];
            /**
             * Asked By
             * Format: uuid
             * @description Player ID of the seeker who asked.
             */
            asked_by: string;
            /**
             * Asked At
             * Format: date-time
             */
            asked_at: string;
            /** @description GeoJSON Point — seeker position when asked. */
            seeker_location_start: components["schemas"]["Point"];
        };
        /**
         * CreateGameRequest
         * @description Create a new game on a map.
         */
        CreateGameRequest: {
            /**
             * Map Id
             * Format: uuid
             * @description ID of the map to play on.
             */
            map_id: string;
            /**
             * Name
             * @description Display name for the host player.
             */
            name: string;
            /**
             * Excluded Stop Ids
             * @description Stop IDs to exclude from play for this game.
             */
            excluded_stop_ids?: string[];
            /**
             * Excluded Route Ids
             * @description Route IDs to exclude from play for this game.
             */
            excluded_route_ids?: string[];
            /**
             * Device Token
             * @description Native push token (APNs or FCM). Optional for game creation.
             */
            device_token?: string | null;
            /**
             * Device Token Provider
             * @description Push provider: "apns" (iOS) or "fcm" (Android).
             * @default apns
             */
            device_token_provider: string;
            /**
             * Hiding Time Min
             * @description Override hiding phase duration. Defaults to map size.
             */
            hiding_time_min?: number | null;
            /**
             * Base Question Delay Min
             * @description Override auto-answer delay. Defaults to 5 minutes.
             */
            base_question_delay_min?: number | null;
        };
        /**
         * EffectiveMapResponse
         * @description The game map with transit data and exclusions applied.
         *
         *     Single source of truth for what the client should render.
         */
        EffectiveMapResponse: {
            /** Name */
            name: string;
            size: components["schemas"]["MapSize"];
            /** @description GeoJSON Polygon. */
            boundary: components["schemas"]["Polygon"];
            /** Districts */
            districts: unknown[];
            /** District Classes */
            district_classes: unknown[];
            /** Stops */
            stops: components["schemas"]["StopResponse"][];
            /** Routes */
            routes: components["schemas"]["RouteResponse"][];
        };
        /**
         * ElectStationRequest
         * @description Elect a hider station — lock in the hiding zone.
         */
        ElectStationRequest: {
            /**
             * Station Id
             * Format: uuid
             * @description ID of the stop to elect as hider station.
             */
            station_id: string;
            /** @description Current hider position as a GeoJSON Point. */
            location: components["schemas"]["Point"];
        };
        /**
         * EndgameExclusionEntryResponse
         * @description One question's exclusion intersected with the hiding zone.
         */
        EndgameExclusionEntryResponse: {
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /**
             * Sequence
             * @description 1-based chronological order within the game.
             */
            sequence: number;
            /**
             * Exclusion
             * @description Exclusion zone intersected with the hiding zone circle.
             */
            exclusion: (components["schemas"]["Point"] | components["schemas"]["MultiPoint"] | components["schemas"]["LineString"] | components["schemas"]["MultiLineString"] | components["schemas"]["Polygon"] | components["schemas"]["MultiPolygon"] | components["schemas"]["GeometryCollection"]) | null;
            /**
             * Total Exclusion
             * @description Cumulative exclusion across endgame-scoped questions.
             */
            total_exclusion: (components["schemas"]["Point"] | components["schemas"]["MultiPoint"] | components["schemas"]["LineString"] | components["schemas"]["MultiLineString"] | components["schemas"]["Polygon"] | components["schemas"]["MultiPolygon"] | components["schemas"]["GeometryCollection"]) | null;
        };
        /**
         * EndgameExclusionsResponse
         * @description Endgame exclusion view — hiding zone geometry and per-question intersected exclusions.
         */
        EndgameExclusionsResponse: {
            /**
             * Hiding Zone
             * @description Hiding zone circle (clipped to game map boundary).
             */
            hiding_zone: components["schemas"]["Point"] | components["schemas"]["MultiPoint"] | components["schemas"]["LineString"] | components["schemas"]["MultiLineString"] | components["schemas"]["Polygon"] | components["schemas"]["MultiPolygon"] | components["schemas"]["GeometryCollection"];
            /** Entries */
            entries: components["schemas"]["EndgameExclusionEntryResponse"][];
        };
        /**
         * ExclusionsResponse
         * @description Seeker tactical view — per-question exclusion geometry and cumulative total.
         */
        ExclusionsResponse: {
            /** Exclusions */
            exclusions: components["schemas"]["QuestionExclusionEntry"][];
            /**
             * Total Exclusion
             * @description Cumulative exclusion across all answered questions.
             */
            total_exclusion: (components["schemas"]["Point"] | components["schemas"]["MultiPoint"] | components["schemas"]["LineString"] | components["schemas"]["MultiLineString"] | components["schemas"]["Polygon"] | components["schemas"]["MultiPolygon"] | components["schemas"]["GeometryCollection"]) | null;
        };
        /**
         * FeatureParamsResponse
         * @description Parameters for a matching or measuring question.
         */
        FeatureParamsResponse: {
            /**
             * Type
             * @enum {string}
             */
            type: "matching" | "measuring";
            /**
             * Category
             * @description Feature category.
             */
            category: string;
            /**
             * Feature Class
             * @description Feature class tier, if applicable.
             */
            feature_class?: number | null;
            /**
             * Source
             * @description Data source (e.g. map_data).
             */
            source: string;
            /** @description Seeker feature resolution. */
            seeker_resolution: components["schemas"]["FeatureResolution"];
            /** @description Hider feature resolution (populated at answer time). */
            hider_resolution?: components["schemas"]["FeatureResolution"] | null;
        };
        /**
         * FeatureResolution
         * @description Resolution result for one player's feature lookup.
         */
        FeatureResolution: {
            /**
             * Feature Id
             * @description Stable identifier of the resolved feature.
             */
            feature_id: string;
            /**
             * Name
             * @description Human-readable name.
             */
            name: string;
            /**
             * Distance
             * @description Distance in convention units.
             */
            distance: number;
        };
        /**
         * GameResponse
         * @description Full game state, including players and question inventory.
         */
        GameResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Map Id
             * Format: uuid
             */
            map_id: string;
            /**
             * Host Player Id
             * Format: uuid
             * @description Player ID of the game's host.
             */
            host_player_id: string;
            status: components["schemas"]["GameStatus"];
            /**
             * Convention
             * @description Distance convention: "metric" or "imperial".
             */
            convention: string;
            /**
             * Join Code
             * @description 4-character code for joining. Null once hiding starts.
             */
            join_code: string | null;
            /**
             * Hiding Time Min
             * @description Hiding phase duration in minutes.
             */
            hiding_time_min: number;
            /**
             * Base Question Delay Min
             * @description Auto-answer delay in minutes.
             */
            base_question_delay_min: number;
            /** @description Question inventory — all slots grouped by type. */
            inventory: components["schemas"]["InventoryResponse"];
            /** Players */
            players: components["schemas"]["PlayerResponse"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Hiding Started At
             * @description When the hiding phase began. Clients compute countdown.
             */
            hiding_started_at?: string | null;
            /**
             * Seeking Started At
             * @description When the seeking phase began.
             */
            seeking_started_at?: string | null;
        };
        /**
         * GameStatus
         * @enum {string}
         */
        GameStatus: "lobby" | "hiding" | "seeking" | "finished" | "dissolved";
        /**
         * GeometryCollection
         * @description GeometryCollection Model
         */
        GeometryCollection: {
            /** Bbox */
            bbox?: [
                number,
                number,
                number,
                number
            ] | [
                number,
                number,
                number,
                number,
                number,
                number
            ] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "GeometryCollection";
            /** Geometries */
            geometries: (components["schemas"]["Point"] | components["schemas"]["MultiPoint"] | components["schemas"]["LineString"] | components["schemas"]["MultiLineString"] | components["schemas"]["Polygon"] | components["schemas"]["MultiPolygon"] | components["schemas"]["GeometryCollection"])[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HiderStationResponse
         * @description The hider's assigned station — includes election status.
         */
        HiderStationResponse: {
            /**
             * Hider Station Id
             * @description Station UUID, or null if not yet assigned (ambiguous/pending).
             */
            hider_station_id: string | null;
            /** @description Current station election status. */
            station_election_status: components["schemas"]["StationElectionStatus"];
        };
        /**
         * HidingZoneResponse
         * @description The hiding zone polygon around a given station.
         */
        HidingZoneResponse: {
            /**
             * Hiding Zone
             * @description Hiding zone polygon (buffer clipped to game map boundary).
             */
            hiding_zone: components["schemas"]["Point"] | components["schemas"]["MultiPoint"] | components["schemas"]["LineString"] | components["schemas"]["MultiLineString"] | components["schemas"]["Polygon"] | components["schemas"]["MultiPolygon"] | components["schemas"]["GeometryCollection"];
        };
        /**
         * InventoryResponse
         * @description Question inventory — all slots grouped by question type.
         */
        InventoryResponse: {
            /**
             * Radar Slots
             * @description Radar question slots.
             */
            radar_slots: components["schemas"]["SlotResponse"][];
            /**
             * Thermometer Slots
             * @description Thermometer question slots.
             */
            thermometer_slots: components["schemas"]["SlotResponse"][];
            /**
             * Matching Slots
             * @description Matching question slots.
             */
            matching_slots: components["schemas"]["SlotResponse"][];
            /**
             * Measuring Slots
             * @description Measuring question slots.
             */
            measuring_slots: components["schemas"]["SlotResponse"][];
        };
        /**
         * JoinGameRequest
         * @description Join an existing game by its join code.
         */
        JoinGameRequest: {
            /**
             * Join Code
             * @description 4-character code shared by the host.
             */
            join_code: string;
            /**
             * Name
             * @description Display name for this player.
             */
            name: string;
            /** @description Optional role to assign on join (hider or seeker). */
            role?: components["schemas"]["PlayerRole"] | null;
            /**
             * Device Token
             * @description Native push token (APNs or FCM). Optional — can be set later via PATCH.
             */
            device_token?: string | null;
            /**
             * Device Token Provider
             * @description Push provider: "apns" (iOS) or "fcm" (Android).
             * @default apns
             */
            device_token_provider: string;
        };
        /**
         * JoinGameResponse
         * @description Returned when a player joins a game — includes credentials for the session.
         */
        JoinGameResponse: {
            game: components["schemas"]["GameResponse"];
            /**
             * Player Id
             * Format: uuid
             * @description The joining player's ID for subsequent requests.
             */
            player_id: string;
            /**
             * Player Secret
             * @description Secret token. Store securely — not retrievable again.
             */
            player_secret: string;
        };
        /**
         * LineString
         * @description LineString Model
         */
        LineString: {
            /** Bbox */
            bbox?: [
                number,
                number,
                number,
                number
            ] | [
                number,
                number,
                number,
                number,
                number,
                number
            ] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "LineString";
            /** Coordinates */
            coordinates: (components["schemas"]["Position2D"] | components["schemas"]["Position3D"])[];
        };
        /**
         * LocationHistoryEntry
         * @description A single location update in the post-game replay log.
         */
        LocationHistoryEntry: {
            /**
             * Player Id
             * Format: uuid
             */
            player_id: string;
            /** @description GeoJSON Point. */
            coordinates: components["schemas"]["Point"];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * LocationReportRequest
         * @description Report the caller's current position.
         */
        LocationReportRequest: {
            /** @description Current position as a GeoJSON Point. */
            coordinates: components["schemas"]["Point"];
            /**
             * Timestamp
             * Format: date-time
             * @description Client-side timestamp of the reading.
             */
            timestamp: string;
        };
        /**
         * MapDetail
         * @description Full map detail including geometry for rendering a preview. Omits stops/routes.
         */
        MapDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            size: components["schemas"]["MapSize"];
            /**
             * Transit Dataset Id
             * Format: uuid
             */
            transit_dataset_id: string;
            /** @description GeoJSON Polygon defining the playable area. */
            boundary: components["schemas"]["Polygon"];
            /**
             * Districts
             * @description District boundaries with id, name, class, and geometry.
             */
            districts: unknown[];
            /**
             * District Classes
             * @description District class definitions (tier + label).
             */
            district_classes: unknown[];
            /**
             * Default Inventory
             * @description Default question inventory for games on this map.
             */
            default_inventory: {
                [key: string]: unknown;
            };
            /**
             * Default Hiding Time Min
             * @description Map-level hiding phase duration override (minutes).
             */
            default_hiding_time_min?: number | null;
            /**
             * Default Base Question Delay Min
             * @description Map-level auto-answer delay override (minutes).
             */
            default_base_question_delay_min?: number | null;
            /** Notes */
            notes: string | null;
        };
        /**
         * MapSize
         * @enum {string}
         */
        MapSize: "small" | "medium" | "large" | "special";
        /**
         * MapSummary
         * @description A map in the browse list — name, size, and region.
         */
        MapSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            size: components["schemas"]["MapSize"];
            /**
             * Region
             * @description Geographic region from the transit dataset.
             */
            region: string;
        };
        /**
         * MultiLineString
         * @description MultiLineString Model
         */
        MultiLineString: {
            /** Bbox */
            bbox?: [
                number,
                number,
                number,
                number
            ] | [
                number,
                number,
                number,
                number,
                number,
                number
            ] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MultiLineString";
            /** Coordinates */
            coordinates: (components["schemas"]["Position2D"] | components["schemas"]["Position3D"])[][];
        };
        /**
         * MultiPoint
         * @description MultiPoint Model
         */
        MultiPoint: {
            /** Bbox */
            bbox?: [
                number,
                number,
                number,
                number
            ] | [
                number,
                number,
                number,
                number,
                number,
                number
            ] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MultiPoint";
            /** Coordinates */
            coordinates: (components["schemas"]["Position2D"] | components["schemas"]["Position3D"])[];
        };
        /**
         * MultiPolygon
         * @description MultiPolygon Model
         */
        MultiPolygon: {
            /** Bbox */
            bbox?: [
                number,
                number,
                number,
                number
            ] | [
                number,
                number,
                number,
                number,
                number,
                number
            ] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MultiPolygon";
            /** Coordinates */
            coordinates: (components["schemas"]["Position2D"] | components["schemas"]["Position3D"])[][][];
        };
        /**
         * NearbyStationResponse
         * @description A playable stop near a given point, with its hiding zone polygon.
         */
        NearbyStationResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Stable Id
             * @description Stable identifier from the transit dataset.
             */
            stable_id: string;
            /** Name */
            name: string;
            /** @description GeoJSON Point. */
            coordinates: components["schemas"]["Point"];
            /**
             * Hiding Zone
             * @description Hiding zone polygon (buffer clipped to game map boundary).
             */
            hiding_zone: components["schemas"]["Point"] | components["schemas"]["MultiPoint"] | components["schemas"]["LineString"] | components["schemas"]["MultiLineString"] | components["schemas"]["Polygon"] | components["schemas"]["MultiPolygon"] | components["schemas"]["GeometryCollection"];
        };
        /**
         * PlayerColor
         * @enum {string}
         */
        PlayerColor: "red" | "blue" | "green" | "orange" | "purple" | "teal" | "pink" | "amber" | "cyan" | "lime" | "indigo" | "coral";
        /**
         * PlayerResponse
         * @description A player in a game.
         */
        PlayerResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** @description Server-assigned player color. */
            color: components["schemas"]["PlayerColor"];
            /** @description Null until the host assigns a role. */
            role: components["schemas"]["PlayerRole"] | null;
        };
        /**
         * PlayerRole
         * @enum {string}
         */
        PlayerRole: "hider" | "seeker";
        /**
         * PlayerUpdate
         * @description Partial update to a player. All fields are optional; only provided fields are applied.
         */
        PlayerUpdate: {
            /**
             * Name
             * @description New display name.
             */
            name?: string | null;
            /** @description New player color. */
            color?: components["schemas"]["PlayerColor"] | null;
            /** @description Assign hider or seeker role. */
            role?: components["schemas"]["PlayerRole"] | null;
            /**
             * Device Token
             * @description Native push token (APNs or FCM).
             */
            device_token?: string | null;
            /**
             * Device Token Provider
             * @description Push provider: "apns" (iOS) or "fcm" (Android).
             * @default apns
             */
            device_token_provider: string;
        };
        /**
         * Point
         * @description Point Model
         */
        Point: {
            /** Bbox */
            bbox?: [
                number,
                number,
                number,
                number
            ] | [
                number,
                number,
                number,
                number,
                number,
                number
            ] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Point";
            /** Coordinates */
            coordinates: components["schemas"]["Position2D"] | components["schemas"]["Position3D"];
        };
        /**
         * Polygon
         * @description Polygon Model
         */
        Polygon: {
            /** Bbox */
            bbox?: [
                number,
                number,
                number,
                number
            ] | [
                number,
                number,
                number,
                number,
                number,
                number
            ] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "Polygon";
            /** Coordinates */
            coordinates: (components["schemas"]["Position2D"] | components["schemas"]["Position3D"])[][];
        };
        Position2D: [
            number,
            number
        ];
        Position3D: [
            number,
            number,
            number
        ];
        /**
         * QuestionDetailResponse
         * @description Full question detail for hiders — everything except exclusion geometry.
         *
         *     Used by the hider detail endpoint and write endpoints (answer/lock-in).
         */
        QuestionDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Game Id
             * Format: uuid
             */
            game_id: string;
            /**
             * Sequence
             * @description 1-based chronological order within the game.
             */
            sequence: number;
            question_type: components["schemas"]["QuestionType"];
            status: components["schemas"]["QuestionStatus"];
            /**
             * Ask Count
             * @description Which attempt this was (1 = first ask).
             */
            ask_count: number;
            /**
             * Parameters
             * @description Type-specific question parameters.
             */
            parameters: components["schemas"]["RadarParamsResponse"] | components["schemas"]["ThermometerParamsResponse"] | components["schemas"]["FeatureParamsResponse"];
            /**
             * Asked By
             * Format: uuid
             * @description Player ID of the seeker who asked.
             */
            asked_by: string;
            /**
             * Asked At
             * Format: date-time
             */
            asked_at: string;
            /** @description GeoJSON Point — seeker position when asked. */
            seeker_location_start: components["schemas"]["Point"];
            /** @description GeoJSON Point — seeker position at lock-in (thermometer only). */
            seeker_location_end: components["schemas"]["Point"] | null;
            /** Answered At */
            answered_at: string | null;
            /** @description GeoJSON Point — hider position at answer time. */
            hider_location: components["schemas"]["Point"] | null;
            /**
             * Answer
             * @description yes/no for radar, closer/farther for thermometer.
             */
            answer: string | null;
        };
        /**
         * QuestionExclusionEntry
         * @description Per-question exclusion geometry for seekers.
         */
        QuestionExclusionEntry: {
            /**
             * Question Id
             * Format: uuid
             */
            question_id: string;
            /**
             * Sequence
             * @description 1-based chronological order within the game.
             */
            sequence: number;
            question_type: components["schemas"]["QuestionType"];
            /**
             * Exclusion
             * @description GeoJSON geometry — the exclusion zone.
             */
            exclusion: (components["schemas"]["Point"] | components["schemas"]["MultiPoint"] | components["schemas"]["LineString"] | components["schemas"]["MultiLineString"] | components["schemas"]["Polygon"] | components["schemas"]["MultiPolygon"] | components["schemas"]["GeometryCollection"]) | null;
        };
        /**
         * QuestionStatus
         * @enum {string}
         */
        QuestionStatus: "asked" | "in_progress" | "answerable" | "answered" | "vetoed" | "abandoned";
        /**
         * QuestionSummaryResponse
         * @description Lightweight question summary — whitelist of safe fields for shared polling.
         *
         *     No parameters, no locations, no geometry. Both roles use this to detect
         *     new activity. New fields added to the question model do not appear here
         *     until consciously included.
         */
        QuestionSummaryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Sequence
             * @description 1-based chronological order within the game.
             */
            sequence: number;
            question_type: components["schemas"]["QuestionType"];
            status: components["schemas"]["QuestionStatus"];
            /**
             * Ask Count
             * @description Which attempt this was (1 = first ask).
             */
            ask_count: number;
            /**
             * Asked By
             * Format: uuid
             * @description Player ID of the seeker who asked.
             */
            asked_by: string;
            /**
             * Asked At
             * Format: date-time
             */
            asked_at: string;
            /** Answered At */
            answered_at: string | null;
            /**
             * Answer
             * @description yes/no for radar, closer/farther for thermometer, etc.
             */
            answer: string | null;
        };
        /**
         * QuestionType
         * @enum {string}
         */
        QuestionType: "radar" | "thermometer" | "matching" | "measuring";
        /**
         * RadarParamsResponse
         * @description Parameters for a radar question.
         */
        RadarParamsResponse: {
            /**
             * Type
             * @default radar
             * @constant
             */
            type: "radar";
            /**
             * Radius
             * @description Radar radius in convention units.
             */
            radius: number;
        };
        /**
         * RemovePlayerRequest
         * @description Body for DELETE /games/{game_id}/players/{player_id}.
         */
        RemovePlayerRequest: {
            /**
             * New Host Id
             * @description Player ID to transfer host to. Required when the host leaves and other players remain.
             */
            new_host_id?: string | null;
        };
        /**
         * RouteResponse
         * @description A transit route on the effective game map, with ordered stop IDs.
         */
        RouteResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Stable Id
             * @description Stable identifier from the transit dataset.
             */
            stable_id: string;
            /** Name */
            name: string;
            /**
             * Color
             * @description Hex color for rendering.
             */
            color: string;
            /**
             * Route Type
             * @description metro, bus, tram, rail, or ferry.
             */
            route_type: string;
            /** @description GeoJSON LineString. */
            shape: components["schemas"]["LineString"];
            /**
             * Stop Ids
             * @description Ordered stop IDs along this route.
             */
            stop_ids: string[];
        };
        /**
         * SessionResponse
         * @description Session validation — confirms the caller is a valid player in the game.
         */
        SessionResponse: {
            player: components["schemas"]["PlayerResponse"];
            game_status: components["schemas"]["GameStatus"];
        };
        /**
         * SlotResponse
         * @description A slot in the question inventory.
         */
        SlotResponse: {
            /**
             * Slot Index
             * @description Original template position (stable across the game).
             */
            slot_index: number;
            /**
             * Distance
             * @description Preset distance or null for custom. Radar/thermometer only.
             */
            distance?: number | null;
            /**
             * Category
             * @description Feature category. Matching/measuring only.
             */
            category?: string | null;
            /**
             * Feature Class
             * @description Feature class tier. Classed categories only.
             */
            feature_class?: number | null;
            /**
             * Ask Count
             * @description Number of times this slot has been used.
             */
            ask_count: number;
        };
        /**
         * StationElectionStatus
         * @enum {string}
         */
        StationElectionStatus: "pending" | "elected" | "auto_assigned" | "ambiguous";
        /**
         * StopResponse
         * @description A transit stop on the effective game map.
         */
        StopResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Stable Id
             * @description Stable identifier from the transit dataset.
             */
            stable_id: string;
            /** Name */
            name: string;
            /** @description GeoJSON Point. */
            coordinates: components["schemas"]["Point"];
        };
        /**
         * ThermometerParamsResponse
         * @description Parameters for a thermometer question.
         */
        ThermometerParamsResponse: {
            /**
             * Type
             * @default thermometer
             * @constant
             */
            type: "thermometer";
            /**
             * Min Travel
             * @description Minimum travel distance in convention units.
             */
            min_travel: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_maps_maps_get: {
        parameters: {
            query?: {
                /** @description Number of items to skip. */
                offset?: number;
                /** @description Maximum number of items to return. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_map_maps__map_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                map_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_game_games_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinGameResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    join_game_games_join_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinGameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinGameResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_state_games__game_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_info_games__game_id__me_get: {
        parameters: {
            query?: never;
            header: {
                "x-player-id": string;
                "x-player-secret": string;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_inventory_games__game_id__inventory_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_player_games__game_id__players__player_id__delete: {
        parameters: {
            query?: never;
            header: {
                "x-player-id": string;
                "x-player-secret": string;
            };
            path: {
                player_id: string;
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RemovePlayerRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_player_games__game_id__players__player_id__patch: {
        parameters: {
            query?: never;
            header: {
                "x-player-id": string;
                "x-player-secret": string;
            };
            path: {
                player_id: string;
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_game_games__game_id__start_post: {
        parameters: {
            query?: never;
            header: {
                "x-player-id": string;
                "x-player-secret": string;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_game_games__game_id__end_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hider_station_games__game_id__hider_station_get: {
        parameters: {
            query?: never;
            header: {
                "x-player-id": string;
                "x-player-secret": string;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HiderStationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    elect_hider_station_games__game_id__hider_station_post: {
        parameters: {
            query?: never;
            header: {
                "x-player-id": string;
                "x-player-secret": string;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ElectStationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HidingZoneResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_nearby_stations_games__game_id__nearby_stations_get: {
        parameters: {
            query: {
                /** @description Latitude of the query point. */
                lat: number;
                /** @description Longitude of the query point. */
                lng: number;
            };
            header: {
                "x-player-id": string;
                "x-player-secret": string;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NearbyStationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hiding_zone_games__game_id__hiding_zone_get: {
        parameters: {
            query: {
                /** @description Stop ID to compute the hiding zone for. */
                station_id: string;
            };
            header: {
                "x-player-id": string;
                "x-player-secret": string;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HidingZoneResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_effective_map_games__game_id__map_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EffectiveMapResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_candidate_stations_games__game_id__candidate_stations_get: {
        parameters: {
            query?: {
                /** @description Pagination offset. */
                offset?: number;
                /** @description Pagination limit. */
                limit?: number;
            };
            header: {
                "x-player-id": string;
                "x-player-secret": string;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StopResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_location_games__game_id__location_post: {
        parameters: {
            query?: never;
            header: {
                "x-player-id": string;
                "x-player-secret": string;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    location_history_games__game_id__location_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationHistoryEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_radar_question_games__game_id__questions_radar_post: {
        parameters: {
            query?: never;
            header: {
                "x-player-id": string;
                "x-player-secret": string;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskQuestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskQuestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_thermometer_question_games__game_id__questions_thermometer_post: {
        parameters: {
            query?: never;
            header: {
                "x-player-id": string;
                "x-player-secret": string;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskQuestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskQuestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_matching_question_games__game_id__questions_matching_post: {
        parameters: {
            query?: never;
            header: {
                "x-player-id": string;
                "x-player-secret": string;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskQuestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskQuestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_measuring_question_games__game_id__questions_measuring_post: {
        parameters: {
            query?: never;
            header: {
                "x-player-id": string;
                "x-player-secret": string;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskQuestionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskQuestionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lock_in_question_games__game_id__questions_thermometer__question_id__lock_in_post: {
        parameters: {
            query?: never;
            header: {
                "x-player-id": string;
                "x-player-secret": string;
            };
            path: {
                question_id: string;
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_question_games__game_id__questions__question_id__answer_post: {
        parameters: {
            query?: never;
            header: {
                "x-player-id": string;
                "x-player-secret": string;
            };
            path: {
                question_id: string;
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    veto_question_games__game_id__questions__question_id__veto_post: {
        parameters: {
            query?: {
                scheduled?: boolean;
            };
            header: {
                "x-player-id": string;
                "x-player-secret": string;
            };
            path: {
                question_id: string;
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abandon_question_endpoint_games__game_id__questions__question_id__abandon_post: {
        parameters: {
            query?: never;
            header: {
                "x-player-id": string;
                "x-player-secret": string;
            };
            path: {
                question_id: string;
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_game_questions_games__game_id__questions_get: {
        parameters: {
            query?: never;
            header: {
                "x-player-id": string;
                "x-player-secret": string;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionSummaryResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_question_detail_games__game_id__questions__question_id__get: {
        parameters: {
            query?: never;
            header: {
                "x-player-id": string;
                "x-player-secret": string;
            };
            path: {
                question_id: string;
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_exclusions_games__game_id__exclusions_get: {
        parameters: {
            query?: never;
            header: {
                "x-player-id": string;
                "x-player-secret": string;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExclusionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    endgame_exclusions_games__game_id__endgame_exclusions_get: {
        parameters: {
            query: {
                /** @description Stop ID to center the hiding zone on. */
                station_id: string;
                /** @description Only include questions with sequence > this value. */
                after_question?: number;
            };
            header: {
                "x-player-id": string;
                "x-player-secret": string;
            };
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndgameExclusionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
