"""use timestamptz for all datetime columns

Flips every datetime column from TIMESTAMP WITHOUT TIME ZONE to
TIMESTAMP WITH TIME ZONE. Existing naive values are interpreted as UTC
via the explicit `<col> AT TIME ZONE 'UTC'` USING clause -- this makes
"everything is UTC" a property of the schema, not a code-review convention.

The change is in-place (no row rewrite); Postgres can flip TIMESTAMP ->
TIMESTAMPTZ without copying when assuming a timezone.

Hand-written rather than autogenerated -- PostGIS autogen emits noise on
this schema (Tiger geocoder drops, false geography modify_type). Same
reason as b4d5b840b4b0_game_timer_pause.

Revision ID: 7b2cab27f4e5
Revises: b4d5b840b4b0
Create Date: 2026-04-28 14:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7b2cab27f4e5'
down_revision: Union[str, Sequence[str], None] = 'b4d5b840b4b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# (table, column, nullable)
_TIMESTAMP_COLUMNS: list[tuple[str, str, bool]] = [
    ('game', 'created_at', False),
    ('game', 'hiding_started_at', True),
    ('game', 'hiding_ends_at', True),
    ('game', 'seeking_started_at', True),
    ('game', 'paused_at', True),
    ('game', 'found_claim_at', True),
    ('game', 'found_claim_expires_at', True),
    ('question', 'asked_at', False),
    ('question', 'answerable_at', True),
    ('question', 'deadline_at', True),
    ('question', 'answered_at', True),
    ('location_update', 'timestamp', False),
    ('device_token', 'updated_at', False),
    ('transit_dataset', 'imported_at', False),
    ('photo_question_params', 'queued_at', True),
    ('photo_question_params', 'submitted_at', True),
    ('photo_question_params', 'reviewed_at', True),
]


def upgrade() -> None:
    """Upgrade schema."""
    for table, column, nullable in _TIMESTAMP_COLUMNS:
        op.alter_column(
            table,
            column,
            existing_type=sa.DateTime(),
            type_=sa.DateTime(timezone=True),
            existing_nullable=nullable,
            postgresql_using=f"{column} AT TIME ZONE 'UTC'",
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table, column, nullable in reversed(_TIMESTAMP_COLUMNS):
        op.alter_column(
            table,
            column,
            existing_type=sa.DateTime(timezone=True),
            type_=sa.DateTime(),
            existing_nullable=nullable,
            postgresql_using=f"{column} AT TIME ZONE 'UTC'",
        )
