"""initial schema with postgis

Revision ID: c8f7386a37e9
Revises:
Create Date: 2026-04-19 16:58:18.250780

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from hideandseek_models.geo_types import ShapelyGeography
from hideandseek_models.geo_types import ShapelyGeometry

# revision identifiers, used by Alembic.
revision: str = 'c8f7386a37e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'device_token',
        sa.Column('player_id', sa.Uuid(), nullable=False),
        sa.Column('token', sa.String(), nullable=False),
        sa.Column('provider', sa.Enum('apns', 'fcm', name='tokenprovider'), nullable=False),
        sa.Column('endpoint_arn', sa.String(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('player_id'),
    )
    op.create_geospatial_table(
        'map_feature',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column(
            'category',
            sa.Enum(
                'transit_line',
                'administrative_area',
                'landmass',
                'high_speed_train_line',
                'rail_station',
                'international_border',
                'admin_division_border',
                'coastline',
                'commercial_airport',
                'mountain',
                'park',
                'amusement_park',
                'zoo',
                'aquarium',
                'golf_course',
                'museum',
                'movie_theater',
                'hospital',
                'library',
                'foreign_consulate',
                name='featurecategory',
            ),
            nullable=False,
        ),
        sa.Column('stable_id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('feature_class', sa.Integer(), nullable=True),
        sa.Column(
            'shape',
            ShapelyGeography(
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text='ST_GeogFromText',
                name='geography',
                nullable=False,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('category', 'stable_id'),
    )
    op.create_geospatial_index(
        'idx_map_feature_shape',
        'map_feature',
        ['shape'],
        unique=False,
        postgresql_using='gist',
        postgresql_ops={},
    )
    op.create_table(
        'transit_dataset',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('region', sa.String(), nullable=False),
        sa.Column('source_url', sa.String(), nullable=True),
        sa.Column('imported_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_geospatial_table(
        'game_map',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column(
            'size', sa.Enum('small', 'medium', 'large', 'special', name='mapsize'), nullable=False
        ),
        sa.Column(
            'convention', sa.Enum('metric', 'imperial', name='distanceconvention'), nullable=False
        ),
        sa.Column('transit_dataset_id', sa.Uuid(), nullable=False),
        sa.Column(
            'boundary',
            ShapelyGeometry(
                geometry_type='MULTIPOLYGON',
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text='ST_GeomFromEWKT',
                name='geometry',
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column('districts', sa.JSON(), nullable=False),
        sa.Column('district_classes', sa.JSON(), nullable=False),
        sa.Column('default_inventory', sa.JSON(), nullable=False),
        sa.Column('default_hiding_time_min', sa.Integer(), nullable=True),
        sa.Column('default_base_question_delay_min', sa.Integer(), nullable=True),
        sa.Column('hiding_zone_radius', sa.Float(), nullable=True),
        sa.Column('tentacle_categories', sa.JSON(), nullable=False),
        sa.Column('notes', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ['transit_dataset_id'],
            ['transit_dataset.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_geospatial_index(
        'idx_game_map_boundary',
        'game_map',
        ['boundary'],
        unique=False,
        postgresql_using='gist',
        postgresql_ops={},
    )
    op.create_geospatial_table(
        'route',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('stable_id', sa.String(), nullable=False),
        sa.Column('dataset_id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('color', sa.String(), nullable=False),
        sa.Column(
            'route_type',
            sa.Enum('metro', 'bus', 'tram', 'rail', 'ferry', name='routetype'),
            nullable=False,
        ),
        sa.Column(
            'shape',
            ShapelyGeography(
                geometry_type='LINESTRING',
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text='ST_GeogFromText',
                name='geography',
                nullable=False,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['dataset_id'],
            ['transit_dataset.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('stable_id', 'dataset_id'),
    )
    op.create_geospatial_index(
        'idx_route_shape',
        'route',
        ['shape'],
        unique=False,
        postgresql_using='gist',
        postgresql_ops={},
    )
    op.create_geospatial_table(
        'stop',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('stable_id', sa.String(), nullable=False),
        sa.Column('dataset_id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column(
            'coordinates',
            ShapelyGeography(
                geometry_type='POINT',
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text='ST_GeogFromText',
                name='geography',
                nullable=False,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['dataset_id'],
            ['transit_dataset.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('stable_id', 'dataset_id'),
    )
    op.create_geospatial_index(
        'idx_stop_coordinates',
        'stop',
        ['coordinates'],
        unique=False,
        postgresql_using='gist',
        postgresql_ops={},
    )
    op.create_table(
        'game',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('map_id', sa.Uuid(), nullable=False),
        sa.Column('host_player_id', sa.Uuid(), nullable=False),
        sa.Column(
            'status',
            sa.Enum('lobby', 'hiding', 'seeking', 'finished', 'dissolved', name='gamestatus'),
            nullable=False,
        ),
        sa.Column('join_code', sa.String(), nullable=True),
        sa.Column('hiding_time_min', sa.Integer(), nullable=False),
        sa.Column('base_question_delay_min', sa.Integer(), nullable=False),
        sa.Column(
            'size', sa.Enum('small', 'medium', 'large', 'special', name='mapsize'), nullable=False
        ),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('hiding_started_at', sa.DateTime(), nullable=True),
        sa.Column('seeking_started_at', sa.DateTime(), nullable=True),
        sa.Column('hider_station_id', sa.Uuid(), nullable=True),
        sa.Column(
            'station_election_status',
            sa.Enum(
                'pending', 'elected', 'auto_assigned', 'ambiguous', name='stationelectionstatus'
            ),
            nullable=False,
        ),
        sa.Column('excluded_stop_ids', sa.JSON(), nullable=False),
        sa.Column('excluded_route_ids', sa.JSON(), nullable=False),
        sa.Column('hiding_zone_radius_override', sa.Float(), nullable=True),
        sa.Column('hiding_zone_expanded', sa.Boolean(), nullable=False),
        sa.Column(
            'proximity_tier',
            sa.Enum('none', 'approaching', 'near', 'entered', name='proximitytier'),
            nullable=False,
        ),
        sa.Column(
            'end_reason',
            sa.Enum('found', 'host_ended', 'dissolved', name='endreason'),
            nullable=True,
        ),
        sa.Column('found_claim_at', sa.DateTime(), nullable=True),
        sa.Column('found_claim_player_id', sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ['hider_station_id'],
            ['stop.id'],
        ),
        sa.ForeignKeyConstraint(
            ['map_id'],
            ['game_map.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_game_join_code'), 'game', ['join_code'], unique=True)
    op.create_table(
        'game_map_feature',
        sa.Column('game_map_id', sa.Uuid(), nullable=False),
        sa.Column('map_feature_id', sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ['game_map_id'],
            ['game_map.id'],
        ),
        sa.ForeignKeyConstraint(
            ['map_feature_id'],
            ['map_feature.id'],
        ),
        sa.PrimaryKeyConstraint('game_map_id', 'map_feature_id'),
    )
    op.create_table(
        'route_stop',
        sa.Column('route_id', sa.Uuid(), nullable=False),
        sa.Column('stop_id', sa.Uuid(), nullable=False),
        sa.Column('sequence', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['route_id'],
            ['route.id'],
        ),
        sa.ForeignKeyConstraint(
            ['stop_id'],
            ['stop.id'],
        ),
        sa.PrimaryKeyConstraint('route_id', 'stop_id', 'sequence'),
    )
    op.create_table(
        'inventory_slot',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('game_id', sa.Uuid(), nullable=False),
        sa.Column(
            'question_type',
            sa.Enum(
                'radar', 'thermometer', 'matching', 'measuring', 'tentacles', name='questiontype'
            ),
            nullable=False,
        ),
        sa.Column('slot_index', sa.Integer(), nullable=False),
        sa.Column('distance', sa.Float(), nullable=True),
        sa.Column(
            'category',
            sa.Enum(
                'transit_line',
                'administrative_area',
                'landmass',
                'high_speed_train_line',
                'rail_station',
                'international_border',
                'admin_division_border',
                'coastline',
                'commercial_airport',
                'mountain',
                'park',
                'amusement_park',
                'zoo',
                'aquarium',
                'golf_course',
                'museum',
                'movie_theater',
                'hospital',
                'library',
                'foreign_consulate',
                name='featurecategory',
            ),
            nullable=True,
        ),
        sa.Column('feature_class', sa.Integer(), nullable=True),
        sa.Column('ask_count', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['game_id'],
            ['game.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_inventory_slot_game_id'), 'inventory_slot', ['game_id'], unique=False)
    op.create_geospatial_table(
        'player',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('game_id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column(
            'color',
            sa.Enum(
                'red',
                'blue',
                'green',
                'orange',
                'purple',
                'teal',
                'pink',
                'amber',
                'cyan',
                'lime',
                'indigo',
                'coral',
                name='playercolor',
            ),
            nullable=False,
        ),
        sa.Column('role', sa.Enum('hider', 'seeker', name='playerrole'), nullable=True),
        sa.Column('secret_hash', sa.String(), nullable=False),
        sa.Column(
            'freeze_location',
            ShapelyGeography(
                geometry_type='POINT',
                dimension=2,
                spatial_index=False,
                from_text='ST_GeogFromText',
                name='geography',
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ['game_id'],
            ['game.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_geospatial_index(
        'idx_player_freeze_location',
        'player',
        ['freeze_location'],
        unique=False,
        postgresql_using='gist',
        postgresql_ops={},
    )
    op.create_geospatial_table(
        'location_update',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('player_id', sa.Uuid(), nullable=False),
        sa.Column('game_id', sa.Uuid(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column(
            'coordinates',
            ShapelyGeography(
                geometry_type='POINT',
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text='ST_GeogFromText',
                name='geography',
                nullable=False,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['game_id'],
            ['game.id'],
        ),
        sa.ForeignKeyConstraint(
            ['player_id'],
            ['player.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_geospatial_index(
        'idx_location_update_coordinates',
        'location_update',
        ['coordinates'],
        unique=False,
        postgresql_using='gist',
        postgresql_ops={},
    )
    op.create_geospatial_table(
        'question',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('game_id', sa.Uuid(), nullable=False),
        sa.Column('sequence', sa.Integer(), nullable=False),
        sa.Column(
            'question_type',
            sa.Enum(
                'radar', 'thermometer', 'matching', 'measuring', 'tentacles', name='questiontype'
            ),
            nullable=False,
        ),
        sa.Column(
            'status',
            sa.Enum(
                'asked',
                'in_progress',
                'answerable',
                'answered',
                'vetoed',
                'abandoned',
                'randomized',
                name='questionstatus',
            ),
            nullable=False,
        ),
        sa.Column('asked_by', sa.Uuid(), nullable=False),
        sa.Column('asked_at', sa.DateTime(), nullable=False),
        sa.Column(
            'seeker_location_start',
            ShapelyGeography(
                geometry_type='POINT',
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text='ST_GeogFromText',
                name='geography',
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            'seeker_location_end',
            ShapelyGeography(
                geometry_type='POINT',
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text='ST_GeogFromText',
                name='geography',
            ),
            nullable=True,
        ),
        sa.Column('answerable_at', sa.DateTime(), nullable=True),
        sa.Column('answered_at', sa.DateTime(), nullable=True),
        sa.Column(
            'hider_location',
            ShapelyGeography(
                geometry_type='POINT',
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text='ST_GeogFromText',
                name='geography',
            ),
            nullable=True,
        ),
        sa.Column('ask_count', sa.Integer(), nullable=False),
        sa.Column('slot_index', sa.Integer(), nullable=False),
        sa.Column('scheduled_veto', sa.Boolean(), nullable=False),
        sa.Column('answer', sa.String(), nullable=True),
        sa.Column(
            'exclusion',
            ShapelyGeometry(
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text='ST_GeomFromEWKT',
                name='geometry',
            ),
            nullable=True,
        ),
        sa.Column(
            'total_exclusion',
            ShapelyGeometry(
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text='ST_GeomFromEWKT',
                name='geometry',
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ['asked_by'],
            ['player.id'],
        ),
        sa.ForeignKeyConstraint(
            ['game_id'],
            ['game.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_geospatial_index(
        'idx_question_exclusion',
        'question',
        ['exclusion'],
        unique=False,
        postgresql_using='gist',
        postgresql_ops={},
    )
    op.create_geospatial_index(
        'idx_question_hider_location',
        'question',
        ['hider_location'],
        unique=False,
        postgresql_using='gist',
        postgresql_ops={},
    )
    op.create_geospatial_index(
        'idx_question_seeker_location_end',
        'question',
        ['seeker_location_end'],
        unique=False,
        postgresql_using='gist',
        postgresql_ops={},
    )
    op.create_geospatial_index(
        'idx_question_seeker_location_start',
        'question',
        ['seeker_location_start'],
        unique=False,
        postgresql_using='gist',
        postgresql_ops={},
    )
    op.create_geospatial_index(
        'idx_question_total_exclusion',
        'question',
        ['total_exclusion'],
        unique=False,
        postgresql_using='gist',
        postgresql_ops={},
    )
    op.create_index(op.f('ix_question_game_id'), 'question', ['game_id'], unique=False)
    op.create_table(
        'feature_question_params',
        sa.Column('question_id', sa.Uuid(), nullable=False),
        sa.Column(
            'category',
            sa.Enum(
                'transit_line',
                'administrative_area',
                'landmass',
                'high_speed_train_line',
                'rail_station',
                'international_border',
                'admin_division_border',
                'coastline',
                'commercial_airport',
                'mountain',
                'park',
                'amusement_park',
                'zoo',
                'aquarium',
                'golf_course',
                'museum',
                'movie_theater',
                'hospital',
                'library',
                'foreign_consulate',
                name='featurecategory',
            ),
            nullable=False,
        ),
        sa.Column('feature_class', sa.Integer(), nullable=True),
        sa.Column('source', sa.String(), nullable=False),
        sa.Column('seeker_feature_id', sa.String(), nullable=False),
        sa.Column('seeker_feature_name', sa.String(), nullable=False),
        sa.Column('seeker_distance', sa.Float(), nullable=False),
        sa.Column('hider_feature_id', sa.String(), nullable=True),
        sa.Column('hider_feature_name', sa.String(), nullable=True),
        sa.Column('hider_distance', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ['question_id'],
            ['question.id'],
        ),
        sa.PrimaryKeyConstraint('question_id'),
    )
    op.create_table(
        'radar_params',
        sa.Column('question_id', sa.Uuid(), nullable=False),
        sa.Column('radius', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ['question_id'],
            ['question.id'],
        ),
        sa.PrimaryKeyConstraint('question_id'),
    )
    op.create_table(
        'tentacle_question_params',
        sa.Column('question_id', sa.Uuid(), nullable=False),
        sa.Column(
            'category',
            sa.Enum(
                'transit_line',
                'administrative_area',
                'landmass',
                'high_speed_train_line',
                'rail_station',
                'international_border',
                'admin_division_border',
                'coastline',
                'commercial_airport',
                'mountain',
                'park',
                'amusement_park',
                'zoo',
                'aquarium',
                'golf_course',
                'museum',
                'movie_theater',
                'hospital',
                'library',
                'foreign_consulate',
                name='featurecategory',
            ),
            nullable=False,
        ),
        sa.Column('poi_ids', sa.JSON(), nullable=False),
        sa.Column('poi_names', sa.JSON(), nullable=False),
        sa.Column('hit', sa.Boolean(), nullable=True),
        sa.Column('hider_feature_id', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ['question_id'],
            ['question.id'],
        ),
        sa.PrimaryKeyConstraint('question_id'),
    )
    op.create_table(
        'thermometer_params',
        sa.Column('question_id', sa.Uuid(), nullable=False),
        sa.Column('min_travel', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ['question_id'],
            ['question.id'],
        ),
        sa.PrimaryKeyConstraint('question_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thermometer_params')
    op.drop_table('tentacle_question_params')
    op.drop_table('radar_params')
    op.drop_table('feature_question_params')
    op.drop_index(op.f('ix_question_game_id'), table_name='question')
    op.drop_geospatial_index(
        'idx_question_total_exclusion',
        table_name='question',
        postgresql_using='gist',
        column_name='total_exclusion',
    )
    op.drop_geospatial_index(
        'idx_question_seeker_location_start',
        table_name='question',
        postgresql_using='gist',
        column_name='seeker_location_start',
    )
    op.drop_geospatial_index(
        'idx_question_seeker_location_end',
        table_name='question',
        postgresql_using='gist',
        column_name='seeker_location_end',
    )
    op.drop_geospatial_index(
        'idx_question_hider_location',
        table_name='question',
        postgresql_using='gist',
        column_name='hider_location',
    )
    op.drop_geospatial_index(
        'idx_question_exclusion',
        table_name='question',
        postgresql_using='gist',
        column_name='exclusion',
    )
    op.drop_geospatial_table('question')
    op.drop_geospatial_index(
        'idx_location_update_coordinates',
        table_name='location_update',
        postgresql_using='gist',
        column_name='coordinates',
    )
    op.drop_geospatial_table('location_update')
    op.drop_geospatial_index(
        'idx_player_freeze_location',
        table_name='player',
        postgresql_using='gist',
        column_name='freeze_location',
    )
    op.drop_geospatial_table('player')
    op.drop_index(op.f('ix_inventory_slot_game_id'), table_name='inventory_slot')
    op.drop_table('inventory_slot')
    op.drop_table('route_stop')
    op.drop_table('game_map_feature')
    op.drop_index(op.f('ix_game_join_code'), table_name='game')
    op.drop_table('game')
    op.drop_geospatial_index(
        'idx_stop_coordinates',
        table_name='stop',
        postgresql_using='gist',
        column_name='coordinates',
    )
    op.drop_geospatial_table('stop')
    op.drop_geospatial_index(
        'idx_route_shape', table_name='route', postgresql_using='gist', column_name='shape'
    )
    op.drop_geospatial_table('route')
    op.drop_geospatial_index(
        'idx_game_map_boundary',
        table_name='game_map',
        postgresql_using='gist',
        column_name='boundary',
    )
    op.drop_geospatial_table('game_map')
    op.drop_table('transit_dataset')
    op.drop_geospatial_index(
        'idx_map_feature_shape',
        table_name='map_feature',
        postgresql_using='gist',
        column_name='shape',
    )
    op.drop_geospatial_table('map_feature')
    op.drop_table('device_token')
    # ### end Alembic commands ###
