#!/usr/bin/env bash
# Run alembic lint + format check.
#
# Ruff-only by design: pyright trips over geoalchemy2's dynamic op
# registration (drop_geospatial_index/table on alembic.op) in the
# autogenerated migrations under alembic/versions/. The checks live at
# the repo root because alembic/ is a sibling of the uv packages, not a
# member; it picks up the root pyproject.toml's [tool.ruff] config.

set -e

uv run ruff check alembic/
uv run ruff format --check alembic/

echo "Alembic checks passed!"
